services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: zephyron_user
      POSTGRES_PASSWORD: zephyron_pass
      POSTGRES_DB: zephyron_hub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: